const freeze = Object.freeze;

export const AIRCRAFT_AUDIO_PROFILES = freeze({
  zero: freeze({
    id: 'zero',
    name: 'A6M Zero radial',
    engineType: 'radial',
    engineEnabled: true,
    baseHz: 44,
    speedHz: 61,
    loadPitchHz: -3.5,
    subharmonicRatio: 0.5,
    subharmonicGain: 0.17,
    harmonicRatios: freeze([1, 1.47, 2.03, 2.56, 3.08, 4.12]),
    harmonicGains: freeze([0.38, 0.18, 0.16, 0.11, 0.09, 0.05]),
    harmonicTypes: freeze(['triangle', 'sawtooth', 'triangle', 'sine', 'sawtooth', 'triangle']),
    detuneCents: freeze([-4, 7, -9, 13, -15, 6]),
    propellerBlades: 3,
    propellerGain: 0.105,
    engineGain: 0.27,
    mechanicalNoiseGain: 0.075,
    lowShelfHz: 115,
    lowShelfDb: 3.2,
    lowpassBaseHz: 920,
    lowpassRangeHz: 1050,
    windGain: 0.20,
    sirenAllowed: false,
  }),
  stuka: freeze({
    id: 'stuka',
    name: 'Ju 87 Stuka inverted V12',
    engineType: 'inverted-v12',
    engineEnabled: true,
    baseHz: 49,
    speedHz: 70,
    loadPitchHz: -2.0,
    subharmonicRatio: 0.5,
    subharmonicGain: 0.08,
    harmonicRatios: freeze([1, 2.01, 2.96, 4.03]),
    harmonicGains: freeze([0.38, 0.26, 0.14, 0.08]),
    harmonicTypes: freeze(['sawtooth', 'triangle', 'sawtooth', 'sine']),
    detuneCents: freeze([-3, 5, -7, 4]),
    propellerBlades: 3,
    propellerGain: 0.09,
    engineGain: 0.245,
    mechanicalNoiseGain: 0.06,
    lowShelfHz: 130,
    lowShelfDb: 2.0,
    lowpassBaseHz: 1020,
    lowpassRangeHz: 1120,
    windGain: 0.19,
    sirenAllowed: true,
  }),
  scout: freeze({
    id: 'scout',
    name: 'Alpine Scout inline',
    engineType: 'inline',
    engineEnabled: true,
    baseHz: 58,
    speedHz: 83,
    loadPitchHz: -1.5,
    subharmonicRatio: 0.5,
    subharmonicGain: 0.05,
    harmonicRatios: freeze([1, 1.98, 3.02, 4.1]),
    harmonicGains: freeze([0.42, 0.23, 0.13, 0.06]),
    harmonicTypes: freeze(['triangle', 'sawtooth', 'triangle', 'sine']),
    detuneCents: freeze([0, 4, -5, 3]),
    propellerBlades: 2,
    propellerGain: 0.075,
    engineGain: 0.205,
    mechanicalNoiseGain: 0.045,
    lowShelfHz: 145,
    lowShelfDb: 1.0,
    lowpassBaseHz: 1120,
    lowpassRangeHz: 1280,
    windGain: 0.19,
    sirenAllowed: false,
  }),
  glider: freeze({
    id: 'glider',
    name: 'Glider wind',
    engineType: 'none',
    engineEnabled: false,
    baseHz: 0,
    speedHz: 0,
    loadPitchHz: 0,
    subharmonicRatio: 0.5,
    subharmonicGain: 0,
    harmonicRatios: freeze([]),
    harmonicGains: freeze([]),
    harmonicTypes: freeze([]),
    detuneCents: freeze([]),
    propellerBlades: 0,
    propellerGain: 0,
    engineGain: 0,
    mechanicalNoiseGain: 0,
    lowShelfHz: 120,
    lowShelfDb: 0,
    lowpassBaseHz: 700,
    lowpassRangeHz: 700,
    windGain: 0.31,
    sirenAllowed: false,
  }),
});

export function resolveAircraftAudioProfile(value) {
  const id = typeof value === 'string' ? value : value?.id;
  return AIRCRAFT_AUDIO_PROFILES[id] || AIRCRAFT_AUDIO_PROFILES.zero;
}

export function isStukaProfile(value) {
  return resolveAircraftAudioProfile(value).id === 'stuka';
}
