export const SOUND_OWNER_KEY = Symbol.for(
  'skyline-vr2.aircraft-warning-audio.owner',
);

export const PHONE_AUDIO_LIMITS = Object.freeze({
  masterLevel: 0.34,
  highpassHz: 38,
  continuousComponentGain: 0.34,
  transientPeakGain: 0.16,
  positionalVoices: 4,
  positionalMaxDistance: 1800,
});

export const SOUND_PROFILES = Object.freeze({
  zero: Object.freeze({
    id: 'zero',
    label: 'A6M Zero radial',
    engine: 'radial',
    engineEnabled: true,
    baseHz: 43,
    cruiseHz: 78,
    highHz: 118,
    subRatio: 0.5,
    harmonicRatios: Object.freeze([1, 1.47, 2.06, 2.93, 4.18]),
    harmonicGains: Object.freeze([0.25, 0.17, 0.13, 0.085, 0.045]),
    noiseGain: 0.052,
    pulseRatio: 0.72,
    pulseGain: 0.064,
    filterBase: 500,
    filterHigh: 1900,
    loadDepth: 0.36,
    windGain: 0.17,
    sirenAllowed: false,
    lowSpeedOn: 27,
    lowSpeedOff: 35,
  }),
  stuka: Object.freeze({
    id: 'stuka',
    label: 'Ju 87 inverted V12',
    engine: 'inverted-v12',
    engineEnabled: true,
    baseHz: 54,
    cruiseHz: 88,
    highHz: 132,
    subRatio: 0.67,
    harmonicRatios: Object.freeze([1, 1.98, 3.03, 4.08, 5.12]),
    harmonicGains: Object.freeze([0.24, 0.19, 0.13, 0.075, 0.04]),
    noiseGain: 0.048,
    pulseRatio: 0.91,
    pulseGain: 0.052,
    filterBase: 620,
    filterHigh: 2200,
    loadDepth: 0.30,
    windGain: 0.17,
    sirenAllowed: true,
    lowSpeedOn: 29,
    lowSpeedOff: 38,
  }),
  scout: Object.freeze({
    id: 'scout',
    label: 'Alpine Scout inline',
    engine: 'inline',
    engineEnabled: true,
    baseHz: 78,
    cruiseHz: 112,
    highHz: 170,
    subRatio: 0.75,
    harmonicRatios: Object.freeze([1, 2.02, 3.1, 4.06, 5.16]),
    harmonicGains: Object.freeze([0.22, 0.15, 0.095, 0.052, 0.028]),
    noiseGain: 0.030,
    pulseRatio: 1.18,
    pulseGain: 0.040,
    filterBase: 820,
    filterHigh: 2850,
    loadDepth: 0.20,
    windGain: 0.16,
    sirenAllowed: false,
    lowSpeedOn: 23,
    lowSpeedOff: 31,
  }),
  glider: Object.freeze({
    id: 'glider',
    label: 'Skyline Glider',
    engine: 'none',
    engineEnabled: false,
    baseHz: 0,
    cruiseHz: 0,
    highHz: 0,
    subRatio: 0,
    harmonicRatios: Object.freeze([1, 1, 1, 1, 1]),
    harmonicGains: Object.freeze([0, 0, 0, 0, 0]),
    noiseGain: 0,
    pulseRatio: 0,
    pulseGain: 0,
    filterBase: 0,
    filterHigh: 0,
    loadDepth: 0,
    windGain: 0.30,
    sirenAllowed: false,
    lowSpeedOn: 18,
    lowSpeedOff: 24,
  }),
});

const ALIASES = Object.freeze({
  a6m: 'zero',
  a6mzero: 'zero',
  'a6m-zero': 'zero',
  ju87: 'stuka',
  'ju-87': 'stuka',
  alpinescout: 'scout',
  'alpine-scout': 'scout',
  skylineglider: 'glider',
  'skyline-glider': 'glider',
});

export function resolveSoundProfile(value) {
  const raw = typeof value === 'string' ? value : value?.id;
  const compact = String(raw || 'zero').toLowerCase().replace(/[^a-z0-9-]/g, '');
  const id = ALIASES[compact] || compact;
  return SOUND_PROFILES[id] || SOUND_PROFILES.zero;
}
